config/routes.rb
Ticketee::Application.routes.draw do
  namespace :api do
    namespace :v1 do
      resources :projects
    end
  end

  namespace :api do
    namespace :v2 do
      resources :projects
    end
  end

  devise_for :users

  resources :projects do
    resources :tickets do
      collection do
        get :search
      end

      member do
        post :watch
      end
    end
  end

  resources :tickets do
    resources :comments
    resources :tags do
      member do
        delete :remove
      end
    end
  end

  root :to => "projects#index"

  namespace :admin do
    root :to => "base#index"
    resources :users do
      resources :permissions
    end
    resources :states do
      member do
        get :make_default
      end
    end
  end

  match '/admin/users/:user_id/permissions', :to => 'admin/permissions#update', :as => :update_user_permissions

  resources :assets
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable, :token_authenticatable

  before_save :ensure_authentication_token

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me

  has_many :tickets
  has_many :permissions

  def self.reset_request_count!
    update_all("request_count = 0", "request_count > 0")
  end

  def to_s
    "#{email} (#{admin? ? "Admin" : "User"})"
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController
  before_filter :find_user, :only => [:show, :edit, :update, :destroy]

  def index
    @users = User.all(:order => "email")
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    set_admin
    if @user.save
      flash[:notice] = t("admin_user.created_msg")
      redirect_to admin_users_path
    else
      flash[:alert] = t("admin_user.not_created_msg")
      render :action => "new"
    end
  end

  def show
  end

  def edit
  end

  def update
    if params[:user][:password].blank?
      params[:user].delete(:password)
      params[:user].delete(:password_confirmation)
    end
    set_admin
    if @user.update_attributes(params[:user])
      flash[:notice] = t("admin_user.updated_msg")
      redirect_to admin_users_path
    else
      flash[:alert] = t("admin_user.not_updated_msg")
      render :action => "edit"
    end
  end

  def destroy
    if @user == current_user
      flash[:alert] = t("admin_user.not_self_deleted_msg")
    else
      @user.destroy
      flash[:notice] = t("admin_user.deleted_msg")
    end

    redirect_to admin_users_path
  end

  private

    def find_user
      @user = User.find(params[:id])
    end

    def set_admin
      @user.admin = params[:user][:admin] == "1"
    end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admin/users/_form.html.erb
<%= form_for [:admin, @user] do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </p>
  <p>
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </p>
  <p>
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </p>
  <p>
    <%= f.check_box :admin %>
    <%= f.label :admin, t("admin_user.is_an_admin") %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/admin/users/edit.html.erb
<% title(t('admin_user.edit_title'), "#{User.model_name.human}") %>
<h2><%= t('admin_user.edit_title') %></h2>
<%= render "form" %>

app/views/admin/users/index.html.erb
<% title("#{User.model_name.human}") %>
<h2><%= "#{User.model_name.human}" %></h2>

<ul>
  <% @users.each do |user| %>
  <li><%= link_to user, [:admin, user] %></li>
  <% end %>
</ul>

<%= link_to t("admin_user.new_title"), new_admin_user_path %>

app/views/admin/users/new.html.erb
<% title( t('admin_user.new_title') ) %>
<h2><%= t('admin_user.new_title') %></h2>
<%= render "form" %>

app/views/admin/users/show.html.erb
<% title("#{User.model_name.human}") %>
<h2><%= @user %></h2>
<%= link_to t("admin_user.edit_title"), edit_admin_user_path(@user) %> |
<%= link_to t("admin_user.delete_title"), admin_user_path(@user), :method => :delete, :confirm => t("admin_user.confirm_delete_msg") %> |
<%= link_to t('admin_user.permissions_title'), admin_user_permissions_path(@user) %>