config/routes.rb
Ticketee::Application.routes.draw do
  namespace :api do
    namespace :v1 do
      resources :projects
    end
  end

  namespace :api do
    namespace :v2 do
      resources :projects
    end
  end

  devise_for :users

  resources :projects do
    resources :tickets do
      collection do
        get :search
      end

      member do
        post :watch
      end
    end
  end

  resources :tickets do
    resources :comments
    resources :tags do
      member do
        delete :remove
      end
    end
  end

  root :to => "projects#index"

  namespace :admin do
    root :to => "base#index"
    resources :users do
      resources :permissions
    end
    resources :states do
      member do
        get :make_default
      end
    end
  end

  match '/admin/users/:user_id/permissions', :to => 'admin/permissions#update', :as => :update_user_permissions

  resources :assets
end

app/models/state.rb
class State < ActiveRecord::Base
  validates_presence_of :name

  def to_s
    name
  end

  def default!
    current_default_state = State.find_by_default(true)
    self.default = true
    self.save!
    if current_default_state
      current_default_state.default = false
      current_default_state.save!
    end
  end
end

app/controllers/admin/states_controller.rb
class Admin::StatesController < ApplicationController
  def index
  end

  def new
    @state = State.new
  end

  def create
    @state = State.new(params[:state])
    if @state.save
      flash[:notice] = t('admin_state.created_msg')
      redirect_to admin_states_path
    else
      flash[:alert] = t('admin_state.not_created_msg')
      render :action => "new"
    end
  end

  def make_default
    @state = State.find(params[:id])
    @state.default!

    flash[:notice] = t("admin_state.make_default_msg", :state_name => @state.name)
    redirect_to admin_states_path
  end
end

app/views/admin/states/_form.html.erb
<%= form_for [:admin, @state] do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :background %><br />
    <%= f.text_field :background %>
  </p>

  <p>
    <%= f.label :color %><br />
    <%= f.text_field :color %>
  </p>
  <%= f.submit %>
<% end %>

app/views/admin/states/index.html.erb
<% title("#{State.model_name.human}") %>
<h2><%= "#{State.model_name.human}" %></h2>

<%= link_to t("admin_state.new_title"), new_admin_state_path %>

<ul id='states'>
<% for state in @states %>
  <li id='state_<%= state.id %>'>
    <%= state.name %>&nbsp;&nbsp;<%= render "states/state", :state => state %>&nbsp;&nbsp;
    <%= link_to t("admin_state.make_default_txt"), make_default_admin_state_path(state) %>
  </li>
<% end %>
</ul>

app/views/admin/states/new.html.erb
<% title( t('admin_state.new_title') ) %>
<h2><%= t('admin_state.new_title') %></h2>
<%= render 'form' %>